// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXSoYj907kWEeWZJDL-Hu8H5YTDwhtYcw',
    appId: '1:802488065006:android:494c390f6ec5a0acd28cff',
    messagingSenderId: '802488065006',
    projectId: 'dict-flutter',
    authDomain: 'dict-firebase-todo.firebaseapp.com',
    storageBucket: 'clinick-app-8a531.appspot.com',
    measurementId: 'G-3MZM3FN95B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXSoYj907kWEeWZJDL-Hu8H5YTDwhtYcw',
    appId: '1:802488065006:android:494c390f6ec5a0acd28cff',
    messagingSenderId: '802488065006',
    projectId: 'clinick-app-8a531',
    storageBucket: 'clinick-app-8a531.appspot.com',
  );
}
